//预声明
export default class Constants {
    static perfect = "res/imgs/perfect.png"
    static again = "res/imgs/again.png"
    static bad = "res/imgs/bad.png"
    static bg = "res/imgs/bg.png"
    static buttonAgain = "res/imgs/buttonAgain.png"
    static buttonNext = "res/imgs/buttonNext.png"
    static buttonStart = "res/imgs/buttonStart.png"
    static buttonW = "res/imgs/buttonW.png"
    static buttonY = "res/imgs/buttonY.png"
    static gesture = "res/imgs/gesture.png"
    static chippy = "res/imgs/1.png"
    static great = "res/imgs/great.png"
    static miss = "res/imgs/miss.png"
    static next = "res/imgs/next.png"
    static snail = "res/imgs/2.png"
    static syrup = "res/imgs/syrup.png"
    static car = "res/imgs/car.png"
    static CountDown1 = "res/imgs/CountDown1.png"
    static CountDown2 = "res/imgs/CountDown2.png"
    static CountDown3 = "res/imgs/CountDown3.png"
    static ready = "res/imgs/ready.png"
    static go = "res/imgs/GO.png"
    static lawn = "res/imgs/lawn.png"
    static lawnON = "res/imgs/lawnON.png"
    static jumpbtn = "res/imgs/jumpbtn.png"
    static jumpbtnON = "res/imgs/jumpbtnON.png"
    static play = "res/imgs/play.png"
    static restart = "res/imgs/restart.png"
    static right = "res/imgs/right.png"
    static sg = "res/imgs/sg.png"
    static starOFF = "res/imgs/starOFF.png"
    static starON = "res/imgs/starON.png"
    static stop = "res/imgs/stop.png"
    static time = "res/imgs/time.png"
    static topBan = "res/imgs/topBan.png"
    static ship = "res/atlas/ship.png"
    
    static sound0 = "sound/321.mp3"
    static sound1 = "sound/button.mp3"
    static sound2 = "sound/beat.mp3"
    static sound3 = "sound/end.mp3"
    static sound4 = "sound/bad.mp3"

}